In [9]:
import pandas as pd
import os
import numpy as np
import re

In [10]:
path =r"C:\Users\fadia\OneDrive\Desktop\Ody\sampel DataBase\Product_History_Reports\Russian_Standard_Gls_Final.csv"
df = pd.read_csv(path)
df.columns

Index(['Date_Russian_Standard_Gls', 'Slot_12_to_18_Russian_Standard_Gls',
       'Slot_18_to_19_Russian_Standard_Gls', 'Base_Price_Russian_Standard_Gls',
       'Slot_12_to_18_Org', 'Slot_18_to_19_Org', 'Base_Price_Hours_Org',
       'Happy_Hour_Russian_Standard_Gls', 'Discount_Russian_Standard_Gls',
       'Unnamed: 9'],
      dtype='object')

In [11]:
df = df[["Date_Russian_Standard_Gls", "Happy_Hour_Russian_Standard_Gls","Discount_Russian_Standard_Gls"]]
df.head()

,Date_Russian_Standard_Gls,Happy_Hour_Russian_Standard_Gls,Discount_Russian_Standard_Gls
0,8/19/2021,Happy Hour 12-6,40
1,8/20/2021,Happy Hour 12-6,40
2,8/21/2021,Happy Hour 12-6,40
3,8/22/2021,Happy Hour 12-6,40
4,8/23/2021,Happy Hour 12-6,40

In [12]:
df.rename(columns={
    "Date_Russian_Standard_Gls": "Date",
    "Happy_Hour_Russian_Standard_Gls": "Happy_Hour",
    "Discount_Russian_Standard_Gls": "Discount"
}, inplace=True)
df.head()

        Date       Happy_Hour  Discount
0  8/19/2021  Happy Hour 12-6        40
1  8/20/2021  Happy Hour 12-6        40
2  8/21/2021  Happy Hour 12-6        40
3  8/22/2021  Happy Hour 12-6        40
4  8/23/2021  Happy Hour 12-6        40

In [13]:
# save to excel file
output_path = r"C:\Users\fadia\OneDrive\Desktop\Ody\Data\original_daily_happy_hour.xlsx"
if not os.path.exists(os.path.dirname(output_path)):
    os.makedirs(os.path.dirname(output_path))
df.to_excel(output_path, index=False)

# save to csv file
output_path = r"C:\Users\fadia\OneDrive\Desktop\Ody\Data\original_daily_happy_hour.csv"
if not os.path.exists(os.path.dirname(output_path)):
    os.makedirs(os.path.dirname(output_path))
df.to_csv(output_path, index=False)